### PR TITLE
Install the correct version of component for all prow jobs

### LINKED ISSUE #721: CI flows on branches should use stable releases
Currently CI flows on branches use nightly releases. For example,

https://gubernator.knative.dev/build/knative-prow/logs/ci-knative-eventing-0.5-continuous/1123145177083416576

fails when installing Istio from the latest Knative Serving nightly. The flow should be using artifacts from Knative Serving 0.5.

@mattmoor @tcnghia to validate the assumption.

### PR DESCRIPTION
**Pull request by Fredy-Z**
Fixes #721 
1. For periodic jobs, set `PULL_BASE_REF` env var to keep consistent with Prow;
2. Use `PULL_BASE_REF` as the branch name for Prow jobs, and `git rev-parse --abbrev-ref HEAD` for non-Prow jobs;
3. I have double checked that `git describe --tags` can get the correct tag from our script.

/cc @adrcunha 
/cc @chaodaiG

### CODE REVIEW

File: scripts/library.sh [hunk 1]
```diff
@@ -445,7 +445,16 @@ function get_canonical_path() {
...
   local knative_base_yaml_source="https://storage.googleapis.com/knative-nightly/@/latest"
-  local branch_name="$(git rev-parse --abbrev-ref HEAD)"
+  local branch_name=""
+  # For non-periodic jobs, we get the branch name from env var set by Prow - https://github.com/kubernetes/test-infra/blob/abcd35c4dbfb0feadd09fc452b533222e3a16b29/prow/jobs.md
+  if [[ -n "${PULL_BASE_REF}" ]]; then
+    branch_name="${PULL_BASE_REF}"
+  fi
+  # For periodic jobs, we only care if it's running against a release branch.
+  # If RELEASE_VERSION is set, branch_name will be the actual release version, like 0.5. Otherwise it will still be an empty string.
+  if [[ -n "${RELEASE_VERSION}" ]]; then
```
Comment (chaodaiG) [inline scripts/library.sh]: I like `git rev-parse` better, as `RELEASE_VERSION` doesn't exist when debugging locally

Comment (Fredy-Z) [reply scripts/library.sh]: Made some changes. Please check the latest code.

File: ci/prow/make_config.go [hunk 2]
```diff
@@ -924,6 +925,13 @@ func generatePeriodic(title string, repoName string, periodicConfig yaml.MapSlic
 		addEnvToJob(&data.Base, "GOOGLE_APPLICATION_CREDENTIALS", data.Base.ServiceAccount)
 		addEnvToJob(&data.Base, "E2E_CLUSTER_REGION", "us-central1")
 	}
+	if version != "" {
+		// If it's a release version, add env var PULL_BASE_REF as ref name of the base branch.
+		// NOTE:
+		// This serves as a workaround since Prow does not have PULL_BASE_REF set for periodic jobs - https://github.com/kubernetes/test-infra/blob/abcd35c4dbfb0feadd09fc452b533222e3a16b29/prow/jobs.md.
+		// We are checking with Kubernetes test-infra team. If we can actually add this env var for all periodic jobs, we can safely delete it here.
+		addEnvToJob(&data.Base, "PULL_BASE_REF", "release-"+version)
```
Comment (adrcunha) [inline ci/prow/make_config.go]: Use `data.Base.RepoBranch`

File: ci/prow/make_config.go [hunk 3]
```diff
@@ -924,6 +925,13 @@ func generatePeriodic(title string, repoName string, periodicConfig yaml.MapSlic
 		addEnvToJob(&data.Base, "GOOGLE_APPLICATION_CREDENTIALS", data.Base.ServiceAccount)
 		addEnvToJob(&data.Base, "E2E_CLUSTER_REGION", "us-central1")
 	}
+	if version != "" {
+		// If it's a release version, add env var PULL_BASE_REF as ref name of the base branch.
+		// NOTE:
+		// This serves as a workaround since Prow does not have PULL_BASE_REF set for periodic jobs - https://github.com/kubernetes/test-infra/blob/abcd35c4dbfb0feadd09fc452b533222e3a16b29/prow/jobs.md.
+		// We are checking with Kubernetes test-infra team. If we can actually add this env var for all periodic jobs, we can safely delete it here.
```
Comment (adrcunha) [inline ci/prow/make_config.go]: Replace this explanation with a TODO and a link to an issue, so we document whatever the outcome is for this case.

File: ci/prow/make_config.go [hunk 4]
```diff
@@ -924,6 +925,13 @@ func generatePeriodic(title string, repoName string, periodicConfig yaml.MapSlic
 		addEnvToJob(&data.Base, "GOOGLE_APPLICATION_CREDENTIALS", data.Base.ServiceAccount)
 		addEnvToJob(&data.Base, "E2E_CLUSTER_REGION", "us-central1")
 	}
+	if version != "" {
```
Comment (adrcunha) [inline ci/prow/make_config.go]: Use `data.Base.RepoBranch`.

File: ci/prow/make_config.go [hunk 5]
```diff
@@ -806,6 +806,7 @@ func generatePeriodic(title string, repoName string, periodicConfig yaml.MapSlic
 	jobNameSuffix := ""
 	jobTemplate := periodicTestJob
 	jobType := ""
+	version := ""
```
Comment (adrcunha) [inline ci/prow/make_config.go]: Revert, since you're gonna use `data.Base.RepoBranch` (see below).

File: scripts/library.sh [hunk 6]
```diff
@@ -445,7 +445,15 @@ function get_canonical_path() {
 # Return the base url we use to build the actual knative yaml sources.
 function get_knative_base_yaml_source() {
   local knative_base_yaml_source="https://storage.googleapis.com/knative-nightly/@/latest"
-  local branch_name="$(git rev-parse --abbrev-ref HEAD)"
+  local branch_name=""
```
Comment (adrcunha) [inline scripts/library.sh]: Join the two assignments, drop the overcomplicated comment; just mention that we get the branch from Prow's env var, by default.

File: ci/prow/make_config.go (hunk 3 above)
Comment (Fredy-Z) [reply ci/prow/make_config.go]: Done.

**Comment by adrcunha** [comment]
/approve

Please update the PR description, it's outdated.

**Comment by Fredy-Z** [comment]
> /approve
> 
> Please update the PR description, it's outdated.

Done.

**Comment by adrcunha** [comment]
Thanks!

/lgtm
