### PR TITLE
flaky-test-retryer: add github integration

### LINKED ISSUE #987: flaky re-trier: Add GitHub integration
Part 4 of implementation of the flaky test re-trier

When our job is triggered by a failing test on a new PR, we will want to re-run those flaky tests until they succeed. We will do this by using the existing GitHub bot to comment `/retest` and a brief message as to why we are doing this

If the PR's failed tests include both flaky and non-flaky tests, we will also post a comment saying why we will not retest until the non-flaky tests are fixed.

### PR DESCRIPTION
**Pull request by TrevorFarrelly**
**What this PR does, why we need it**:
This PR adds GitHub commenting functionality to the flaky-test-retryer. The comments feature a list of jobs, the number of retries, and either a list of tests that prevent the job from restarting or the command to restart the test. [Example](https://github.com/TrevorFarrelly/knative-testing/pull/30)

When we update a comment, we have to delete and re-post it so knative-prow robot detects a new `/test <job>` command. This does cause some GitHub email notification spam, and unfortunately I could not find another easy solution.

If any Knative devs have ideas for different comment formatting, or other ways to restart the jobs, I'd love for some input. The retryer is meant to help you after all, not spam your inbox any more than necessary :)

**Which issue(s) this PR fixes**:
Fixes #987 

**Special notes to reviewers**:

**User-visible changes in this PR**:

### CODE REVIEW

**Comment by chaodaiG** [comment]
/cc @adrcunha 
He gave me pretty good suggestions on Flaky test reporter tool

File: shared/ghutil/issue.go [hunk 1]
```diff
@@ -199,6 +199,19 @@ func (gc *GithubClient) EditComment(org, repo string, commentID int64, commentBo
 	return err
 }
 
+// DeleteComment deletes comment from issue
+func (gc *GithubClient) DeleteComment(org, repo string, commentID int64) error {
```
Comment (chaodaiG) [inline shared/ghutil/issue.go]: I think you need to add this to the Interface to make unit test work

File: tools/flaky-test-retryer/github_commenter.go [hunk 2]
```diff
@@ -37,3 +53,107 @@ func NewGithubClient(githubAccount string) (*GithubClient, error) {
...
+	}
+	return fmt.Sprintf(commentTemplate, strings.Join(entryString, "\n"), cmd), entries[jd.JobName] <= maxRetries
+}
+
+// buildRetryString increments the retry counter and generates a /test string if we have
+// more retries available.
+func buildRetryString(job string, entries map[string]int) string {
+	entries[job]++
+	if entries[job] <= maxRetries {
+		return fmt.Sprintf("Automatically retrying...\n/test %s", job)
```
Comment (chaodaiG) [inline tools/flaky-test-retryer/github_commenter.go]: How about listing tests that are flaky here? This can make the logic of `buildRetryString` and `buildNoRetryString` share majority of the logic

File: tools/flaky-test-retryer/github_commenter.go [hunk 3]
```diff
@@ -37,3 +53,107 @@ func NewGithubClient(githubAccount string) (*GithubClient, error) {
...
+	}
+	return ""
+}
+
+// buildNoRetryString formats the tests that prevent us from retrying into a drop-down
+// menu underneath the table of retries.
+func buildNoRetryString(job string, outliers []string) string {
+	dropdownFmt := "<details>\n<summary>Non-flaky failing tests preventing automatic retry of %s:</summary>\n<br>\n<code>%s</code>\n</details>"
```
Comment (chaodaiG) [inline tools/flaky-test-retryer/github_commenter.go]: I'm not sure about hiding them is the best idea. If the purpose is to avoid displaying too long message, I would recommend doing the first 10 tests then add another line saying `X more tests also failed`

File: tools/flaky-test-retryer/github_commenter.go [hunk 4]
```diff
@@ -37,3 +53,107 @@ func NewGithubClient(githubAccount string) (*GithubClient, error) {
...
+}
+
+// getOldComment queries the GitHub PR specified and gets the comment made by us. If no comment
+// is found, we do not error, since we will be creating a new one anyways.
+func (gc *GithubClient) getOldComment(org, repo string, pull int) (*github.IssueComment, error) {
+	comments, err := gc.ListComments(org, repo, pull)
+	if err != nil {
+		return nil, err
+	}
+	user, err := gc.GetGithubUser()
```
Comment (chaodaiG) [inline tools/flaky-test-retryer/github_commenter.go]: I would prefer collect this information up ahead of time, and store it in gc

File: tools/flaky-test-retryer/github_commenter.go [hunk 5]
```diff
@@ -37,3 +53,107 @@ func NewGithubClient(githubAccount string) (*GithubClient, error) {
...
+	if err != nil {
+		return nil, err
+	}
+	for _, comment := range comments {
```
Comment (chaodaiG) [inline tools/flaky-test-retryer/github_commenter.go]: a comment here would be helpful, like `this robot should only leave one comment in a PR`. And a guard here might be even better

File: tools/flaky-test-retryer/handler.go [hunk 6]
```diff
@@ -94,16 +96,16 @@ func (hc *HandlerClient) HandleJob(jd *JobData) {
 	}
 	logWithPrefix(jd, "got %d flaky tests from today's report\n", len(flakyTests))
 
-	if outliers := getNonFlakyTests(failedTests, flakyTests); len(outliers) > 0 {
+	outliers := getNonFlakyTests(failedTests, flakyTests)
+	if len(outliers) > 0 {
```
Comment (chaodaiG) [inline tools/flaky-test-retryer/handler.go]: this if condition is done twice, does this logic have to be here?

File: tools/flaky-test-retryer/main.go [hunk 7]
```diff
@@ -34,13 +34,14 @@ const (
...
 	githubAccount := flag.String("github-account", "", "Token file for Github authentication")
+	dryrun := flag.Bool("dry-run", false, "dry run switch")
 	flag.Parse()
 
 	if err := InitLogParser(*serviceAccount); nil != err {
 		log.Fatalf("Failed authenticating GCS: '%v'", err)
 	}
 
-	handler, err := NewHandlerClient(*githubAccount)
+	handler, err := NewHandlerClient(*githubAccount, *dryrun)
```
Comment (chaodaiG) [inline tools/flaky-test-retryer/main.go]: I feel like this can be done slightly different, like https://github.com/knative/pkg/blob/e4bc08cc8deda3eac40a8d53984d09c9d0e1ad48/test/e2e_flags.go#L48

File: shared/ghutil/fakeghutil/fakeghutil.go [hunk 8]
```diff
@@ -160,6 +160,17 @@ func (fgc *FakeGithubClient) EditComment(org, repo string, commentID int64, comm
 	return nil
 }
 
+// DeleteComment deletes comment from issue
+func (gc *GithubClient) DeleteComment(org, repo string, commentID int64) error {
```
Comment (srinivashegde86) [inline shared/ghutil/fakeghutil/fakeghutil.go]:
```suggestion
func (fgc *FakeGithubClient) DeleteComment(org, repo string, commentID int64) error {
```

File: tools/flaky-test-retryer/github_commenter.go [hunk 9]
```diff
@@ -21,9 +21,25 @@ limitations under the License.
...
+	"log"
+	"regexp"
+	"strconv"
+	"strings"
+
+	"github.com/google/go-github/github"
 	"github.com/knative/test-infra/shared/ghutil"
 )
 
+const (
```
Comment (srinivashegde86) [inline tools/flaky-test-retryer/github_commenter.go]:
```suggestion
const maxRetries = 3
```

File: tools/flaky-test-retryer/github_commenter.go [hunk 10]
```diff
@@ -21,9 +21,25 @@ limitations under the License.
...
+	maxRetries = 3
+)
+
+var (
+	commentTemplate = "The following tests failed due to flakiness:\n\n" +
```
Comment (srinivashegde86) [inline tools/flaky-test-retryer/github_commenter.go]:
```suggestion
	commentTemplate = "The following tests are currently flaky. Running them again to verify...:\n\n" +
```

File: tools/flaky-test-retryer/github_commenter.go [hunk 11]
```diff
@@ -37,3 +53,107 @@ func NewGithubClient(githubAccount string) (*GithubClient, error) {
...
+		if *comment.GetUser().Login == *user.Login {
+			return comment, nil
+		}
+	}
+	return nil, nil
+}
+
+// parseEntries collects retry information from the given comment, so we can reuse it in
+// a new comment.
+func parseEntries(comment *github.IssueComment) (map[string]int, error) {
```
Comment (srinivashegde86) [inline tools/flaky-test-retryer/github_commenter.go]: I would like to see some unit tests around this.

File: tools/flaky-test-retryer/handler.go (hunk 6 above)
Comment (TrevorFarrelly) [reply tools/flaky-test-retryer/handler.go]: this was so I could log how many tests are not flaky and whether or not we triggered a retry. I could move the logic, or forgo it altogether as it's mostly for testing purposes

Comment (chaodaiG) [reply tools/flaky-test-retryer/handler.go]: This would be helpful debugging message, just think it could be combined with the other `if else` if you agree with what I suggested over there

File: tools/flaky-test-retryer/github_commenter.go (hunk 3 above)
Comment (TrevorFarrelly) [reply tools/flaky-test-retryer/github_commenter.go]: updated format, see the new examples at the same link above.

File: tools/flaky-test-retryer/github_commenter.go (hunk 4 above)
Comment (TrevorFarrelly) [reply tools/flaky-test-retryer/github_commenter.go]: added Login field to gc, populated in the constructor

File: tools/flaky-test-retryer/github_commenter.go [hunk 12]
```diff
@@ -37,3 +53,107 @@ func NewGithubClient(githubAccount string) (*GithubClient, error) {
...
+			return err
+		}
+	}
+	_, err = gc.CreateComment(jd.Refs[0].Org, jd.Refs[0].Repo, jd.Refs[0].Pulls[0].Number, newComment)
+	return err
+}
+
+// getOldComment queries the GitHub PR specified and gets the comment made by us. If no comment
+// is found, we do not error, since we will be creating a new one anyways.
+func (gc *GithubClient) getOldComment(org, repo string, pull int) (*github.IssueComment, error) {
```
[the remark this answers is not in the document]
Comment (TrevorFarrelly) [reply tools/flaky-test-retryer/github_commenter.go]: fixed, added a tag to the beginning of the comment in addition to username

File: tools/flaky-test-retryer/github_commenter.go (hunk 10 above)
Comment (TrevorFarrelly) [reply tools/flaky-test-retryer/github_commenter.go]: fixed

File: shared/ghutil/fakeghutil/fakeghutil.go (hunk 8 above)
Comment (TrevorFarrelly) [reply shared/ghutil/fakeghutil/fakeghutil.go]: fixed

File: tools/flaky-test-retryer/handler.go (hunk 6 above)
Comment (TrevorFarrelly) [reply tools/flaky-test-retryer/handler.go]: done

File: tools/flaky-test-retryer/github_commenter.go (hunk 5 above)
Comment (TrevorFarrelly) [reply tools/flaky-test-retryer/github_commenter.go]: commented, I will add a check in another commit

File: shared/ghutil/issue.go (hunk 1 above)
Comment (TrevorFarrelly) [reply shared/ghutil/issue.go]: fixed

File: tools/flaky-test-retryer/github_commenter.go (hunk 9 above)
Comment (TrevorFarrelly) [reply tools/flaky-test-retryer/github_commenter.go]: added a new const in other changes

File: tools/flaky-test-retryer/github_commenter.go (hunk 2 above)
Comment (TrevorFarrelly) [reply tools/flaky-test-retryer/github_commenter.go]: As it stands, I don't collect the flaky tests that affect this job, only the outliers, so this will require some more logic elsewhere. Do you think it would be helpful from a development perspective, seeing which flaky tests affected that job?

Comment (chaodaiG) [reply tools/flaky-test-retryer/github_commenter.go]: No one probably would even pay attention to that, but from my point of view, it would be useful for checking if this tool works properly

File: tools/flaky-test-retryer/main.go (hunk 7 above)
Comment (TrevorFarrelly) [reply tools/flaky-test-retryer/main.go]: moved all flags to that format, not necessary but figured I'd do it for consistency

File: tools/flaky-test-retryer/github_commenter.go (hunk 5 above)
Comment (TrevorFarrelly) [reply tools/flaky-test-retryer/github_commenter.go]: added a check and solution if there's more than one comment, it's a little strange though so I'd like your input.

File: tools/flaky-test-retryer/github_commenter.go [hunk 13]
```diff
@@ -35,5 +54,152 @@ func NewGithubClient(githubAccount string) (*GithubClient, error) {
...
+		return comments[i].GetCreatedAt().Unix() < comments[i].GetCreatedAt().Unix()
+	})
+
+	switch len(matches) {
+	case 0:
+		return nil, nil
+	case 1:
+		return matches[0], nil
+	default:
+		if Flags.DryRun {
```
Comment (chaodaiG) [inline tools/flaky-test-retryer/github_commenter.go]: I think relying on a global var would make unit test a bit harder, add it to `gc` might be an option

File: tools/flaky-test-retryer/github_commenter.go (hunk 5 above)
Comment (chaodaiG) [reply tools/flaky-test-retryer/github_commenter.go]: yep, this is strange, I would prefer it to fail since this is not suppose to happen. We can discuss how to surface this kind of problem

File: tools/flaky-test-retryer/github_commenter.go (hunk 11 above)
Comment (TrevorFarrelly) [reply tools/flaky-test-retryer/github_commenter.go]: working on a more comprehensive unit test for all of github_commenter, I'll get that in ASAP

Comment (TrevorFarrelly) [reply tools/flaky-test-retryer/github_commenter.go]: alright, github_commenter_test.go is up. I will continue to add more test cases to the rest of the retryer over time.

File: tools/flaky-test-retryer/github_commenter.go (hunk 13 above)
Comment (TrevorFarrelly) [reply tools/flaky-test-retryer/github_commenter.go]: done

File: tools/flaky-test-retryer/github_commenter_test.go [hunk 14]
```diff
@@ -0,0 +1,191 @@
...
+func TestGetOldComment(t *testing.T) {
+	gc := getFakeGithubClient()
+	cases := []struct {
+		client      *GithubClient
+		org, repo   string
+		pull        int
+		wantComment *github.IssueComment
+		wantErr     error
+	}{
+		{gc, fakeOrg, fakeRepo, fakePullID, nil, nil},
```
Comment (chaodaiG) [inline tools/flaky-test-retryer/github_commenter_test.go]: nit, this test is different from what most table-driven tests, since the order matters, you may want to add a comment here

**Comment by chaodaiG** [comment]
/ok-to-test
/approve

feel free fix/ignore with the nit I left. will let @srinivashegde86 lgtm

File: tools/flaky-test-retryer/github_commenter.go [hunk 15]
```diff
@@ -21,19 +21,175 @@ limitations under the License.
...
+	// this robot should only leave one comment in a given PR. Collect everything with our identifier,
+	// just in case.
+	var matches []*github.IssueComment
+	for _, comment := range comments {
+		match, err := regexp.Match(identifier, []byte(comment.GetBody()))
+		if err != nil {
+			return nil, err
+		}
+		if match && *comment.GetUser().Login == gc.Login {
+			matches = append(matches, comment)
```
Comment (srinivashegde86) [inline tools/flaky-test-retryer/github_commenter.go]: whats the point of using an array, if this should never have >1 ? Why not just have a var. If we really want to be sure that we are not doing this twice, we can err out when the condition is true and var is set.

File: tools/flaky-test-retryer/github_commenter.go [hunk 16]
```diff
@@ -21,19 +21,175 @@ limitations under the License.
...
+		}
+	}
+
+	switch len(matches) {
```
Comment (srinivashegde86) [inline tools/flaky-test-retryer/github_commenter.go]: I dont think this switch is necessary. Have just one var and return var, err

File: tools/flaky-test-retryer/github_commenter_test.go (hunk 14 above)
Comment (TrevorFarrelly) [reply tools/flaky-test-retryer/github_commenter_test.go]: gotcha, added a comment

File: tools/flaky-test-retryer/github_commenter_test.go [hunk 17]
```diff
@@ -0,0 +1,192 @@
...
+	}
+	for _, data := range cases {
+		actual, _ := parseEntries(data.input)
+		if !reflect.DeepEqual(actual, data.want) {
+			t.Fatalf("parse entries: got '%v', want '%v'", actual, data.want)
+		}
+	}
+}
+
+func TestBuildNewComment(t *testing.T) {
```
Comment (srinivashegde86) [inline tools/flaky-test-retryer/github_commenter_test.go]: add one for testParseentries as well

File: tools/flaky-test-retryer/github_commenter.go [hunk 18]
```diff
@@ -21,19 +21,175 @@ limitations under the License.
...
+	oldEntries, err := parseEntries(oldComment)
+	if err != nil {
+		return err
+	}
+	if _, ok := oldEntries[jd.JobName]; !ok {
+		oldEntries[jd.JobName] = 0
+	}
+	newComment, canRetry := buildNewComment(jd, oldEntries, outliers)
+	if !canRetry {
+		return fmt.Errorf("expended all %d retries", maxRetries)
```
[the remark this answers is not in the document]
Comment (TrevorFarrelly) [reply tools/flaky-test-retryer/github_commenter.go]: The old comment would say 3/3 retries in this case so I figured it was implied. I can post a comment explicitly stating that if it makes sense.

File: tools/flaky-test-retryer/github_commenter.go (hunk 15 above)
Comment (TrevorFarrelly) [reply tools/flaky-test-retryer/github_commenter.go]: done

File: tools/flaky-test-retryer/github_commenter.go (hunk 16 above)
Comment (TrevorFarrelly) [reply tools/flaky-test-retryer/github_commenter.go]: done

File: tools/flaky-test-retryer/github_commenter_test.go (hunk 17 above)
Comment (TrevorFarrelly) [reply tools/flaky-test-retryer/github_commenter_test.go]: do you mean a case in TestBuildNewComment or a TestParseEntries? because TestParseEntries is written [here](https://github.com/knative/test-infra/pull/1165/files/e31bff94147128bed54d2d9fb2eb59a6be704801#diff-00576b64e8131e8f783bc75ba0c4d685R154).

File: tools/flaky-test-retryer/github_commenter.go (hunk 18 above)
[the remark this answers is not in the document]
Comment (srinivashegde86) [reply tools/flaky-test-retryer/github_commenter.go]: yes. But, the comment will say attempt #3/3. But, there will be no result from that attempt. Having a different message like `Attempted 3 times and failed` is more explicit.

**Comment by srinivashegde86** [comment]
/lgtm
/hold
There is one nit about the last attempt comment. Cancel hold with `/hold cancel` if you think its not needed.

File: tools/flaky-test-retryer/github_commenter.go (hunk 18 above)
[the remark this answers is not in the document]
Comment (TrevorFarrelly) [reply tools/flaky-test-retryer/github_commenter.go]: done
