### PR TITLE
Fix the logic to find the latest release build for the given repo

### LINKED ISSUE #723: Eventing-0.5 and eventing-sources-0.5 tests are consistently failing
These two jobs are consistently failing. 
https://testgrid.knative.dev/knative-eventing-0.5#continuous
https://testgrid.knative.dev/knative-eventing-sources-0.5#continuous

In the logs, we can see the following error:
```
I0430 08:51:06.371] unable to recognize "https://storage.googleapis.com/knative-nightly/serving/latest/istio.yaml": no matches for kind "attributemanifest" in version "config.istio.io/v1alpha2"
I0430 08:51:06.372] unable to recognize "https://storage.googleapis.com/knative-nightly/serving/latest/istio.yaml": no matches for kind "attributemanifest" in version "config.istio.io/v1alpha2"
I0430 08:51:06.372] unable to recognize "https://storage.googleapis.com/knative-nightly/serving/latest/istio.yaml": no matches for kind "handler" in version "config.istio.io/v1alpha2"
I0430 08:51:06.372] unable to recognize "https://storage.googleapis.com/knative-nightly/serving/latest/istio.yaml": no matches for kind "rule" in version "config.istio.io/v1alpha2"
I0430 08:51:06.372] unable to recognize "https://storage.googleapis.com/knative-nightly/serving/latest/istio.yaml": no matches for kind "rule" in version "config.istio.io/v1alpha2"
I0430 08:51:06.372] unable to recognize "https://storage.googleapis.com/knative-nightly/serving/latest/istio.yaml": no matches for kind "kubernetes" in version "config.istio.io/v1alpha2"
I0430 08:51:06.372] unable to recognize "https://storage.googleapis.com/knative-nightly/serving/latest/istio.yaml": no matches for kind "DestinationRule" in version "networking.istio.io/v1alpha3"
I0430 08:51:06.372] unable to recognize "https://storage.googleapis.com/knative-nightly/serving/latest/istio.yaml": no matches for kind "DestinationRule" in version "networking.istio.io/v1alpha3"
I0430 08:51:06.379] ERROR: Knative setup failed
```

### PR DESCRIPTION
**Pull request by Fredy-Z**
As part of Fixes #723 

Update the logic to find the latest release build for other repos, given the repo that is being tested:
- On a master branch, use `nightly build`;
- On a release branch, get the branch version, then for each particular module, find the latest version of that particular branch by inspecting gs://knative-releases

### CODE REVIEW

**Comment by Fredy-Z** [comment]
It's failing due to https://github.com/knative/test-infra/issues/829

File: scripts/library.sh [hunk 1]
```diff
@@ -487,9 +490,34 @@ function get_knative_base_yaml_source() {
...
+
+# Returns latest release yaml source for the given knative project.
+# Parameters: $1 - git tag name of the current branch, e.g. v0.5.1
+#             $2 - repository name of the given project
+#             $3 - short name of the yaml source file
+function find_latest_release_yaml_source() {
+  local tag_name=$1
+  local repo_name=$2
+  local source_name=$3
+  local major_minor=`echo $tag_name | cut -d. -f-2`
```
Comment (adrcunha) [inline scripts/library.sh]: Use "$()", here and everywhere.

File: scripts/library.sh [hunk 2]
```diff
@@ -487,9 +490,34 @@ function get_knative_base_yaml_source() {
...
+  local revision=`echo $tag_name | cut -d. -f3`
+  for (( ; revision>=0; revision-- ))
+  do
+    local tag_name="$major_minor.$revision"
+    local yaml_source="https://storage.googleapis.com/knative-releases/${repo_name}/previous/${tag_name}/${source_name}.yaml"
+    local ret_code=$(curl -s -o /dev/null -w "%{http_code}" "${yaml_source}")
```
Comment (adrcunha) [inline scripts/library.sh]: Use `gsutil ls` and parse the output, it's faster and simpler.

File: scripts/library.sh [hunk 3]
```diff
@@ -487,9 +490,34 @@ function get_knative_base_yaml_source() {
   if [[ ${branch_name} =~ ^release-[0-9\.]+$ ]]; then
     # Get the latest tag name for the current branch, which is likely formatted as v0.5.0
     local tag_name="$(git describe --tags --abbrev=0)"
-    knative_base_yaml_source="https://storage.googleapis.com/knative-releases/@/previous/${tag_name}"
+    # The other repo might not have this tag, so we need to find the first available tag before it.
+    echo "$(find_latest_release_yaml_source ${tag_name} ${repo_name} ${source_name})"
+  else
+    local knative_base_yaml_source="https://storage.googleapis.com/knative-nightly/@/latest"
+    echo "${knative_base_yaml_source/@/${repo_name}}/${source_name}.yaml"
```
Comment (adrcunha) [inline scripts/library.sh]: The string replacement is not useful anymore, making this hard to read. Just assemble the final string, here.

File: scripts/library.sh (hunk 2 above)
Comment (Fredy-Z) [reply scripts/library.sh]: Done.

File: scripts/library.sh (hunk 1 above)
Comment (Fredy-Z) [reply scripts/library.sh]: Done.

File: scripts/library.sh [hunk 4]
```diff
@@ -475,21 +475,51 @@ function get_canonical_path() {
...
+# Parameters: $1 - git tag name of the current branch, e.g. v0.5.1
+#             $2 - repository name of the given project
+#             $3 - short name of the yaml source file
+function find_latest_release_yaml_source() {
+  local tag_name=$1
+  local repo_name=$2
+  local source_name=$3
+  local major_minor="$(echo ${tag_name} | cut -d. -f-2)"
+  local revision="$(echo ${tag_name} | cut -d. -f3)"
+  for (( ; revision>=0; revision-- ))
```
Comment (adrcunha) [inline scripts/library.sh]: Drop the loop; list the dir, filter the subdirs by major/minor version, then reverse sort the list and use the first entry.

Comment (Fredy-Z) [reply scripts/library.sh]: Thanks for the suggestion!
Apparently I went the wrong direction, as I didn't know we can use `gsutil` in our scripts.
I have simplified the logic by using `gsutil ls` and `tail` and I have tested it's working.

File: scripts/library.sh [hunk 5]
```diff
@@ -475,21 +475,28 @@ function get_canonical_path() {
...
   [[ -z "${branch_name}" ]] && branch_name="$(git rev-parse --abbrev-ref HEAD)"
-  # If it's a release branch, base URL should point to a specific version.
+  # If it's a release branch, the yaml source URL should point to a specific version.
   if [[ ${branch_name} =~ ^release-[0-9\.]+$ ]]; then
     # Get the latest tag name for the current branch, which is likely formatted as v0.5.0
     local tag_name="$(git describe --tags --abbrev=0)"
-    knative_base_yaml_source="https://storage.googleapis.com/knative-releases/@/previous/${tag_name}"
+    # The given repo might not have this tag, so we need to find its latest release manifest with the same major&minor version.
+    local major_minor="$(echo ${tag_name} | cut -d. -f-2)"
+    echo "$(gsutil ls gs://knative-releases/${repo_name}/previous/${major_minor}.*/${yaml_name}.yaml | tail -n 1)"
```
Comment (adrcunha) [inline scripts/library.sh]: You'll have to break this line into multiple steps because:
1. You're returning a gs URL, not an https URL.
1. gsutil ls doesn't guarantee the listing is sorted, so better use `sort` to ensure it.

File: scripts/library.sh [hunk 6]
```diff
@@ -475,21 +475,28 @@ function get_canonical_path() {
...
   (( IS_PROW )) && branch_name="${PULL_BASE_REF:-}"
   [[ -z "${branch_name}" ]] && branch_name="$(git rev-parse --abbrev-ref HEAD)"
-  # If it's a release branch, base URL should point to a specific version.
+  # If it's a release branch, the yaml source URL should point to a specific version.
   if [[ ${branch_name} =~ ^release-[0-9\.]+$ ]]; then
     # Get the latest tag name for the current branch, which is likely formatted as v0.5.0
     local tag_name="$(git describe --tags --abbrev=0)"
-    knative_base_yaml_source="https://storage.googleapis.com/knative-releases/@/previous/${tag_name}"
+    # The given repo might not have this tag, so we need to find its latest release manifest with the same major&minor version.
+    local major_minor="$(echo ${tag_name} | cut -d. -f-2)"
```
Comment (adrcunha) [inline scripts/library.sh]:
```suggestion
    local major_minor="$(echo ${tag_name} | cut -d. -f1-2)"
```

File: scripts/library.sh (hunk 5 above)
Comment (Fredy-Z) [reply scripts/library.sh]: Sorry I forgot the gs URL when I made the change.
Done.

File: scripts/library.sh [hunk 7]
```diff
@@ -491,8 +491,12 @@ function get_latest_knative_yaml_source() {
     # Get the latest tag name for the current branch, which is likely formatted as v0.5.0
     local tag_name="$(git describe --tags --abbrev=0)"
     # The given repo might not have this tag, so we need to find its latest release manifest with the same major&minor version.
-    local major_minor="$(echo ${tag_name} | cut -d. -f-2)"
-    echo "$(gsutil ls gs://knative-releases/${repo_name}/previous/${major_minor}.*/${yaml_name}.yaml | tail -n 1)"
+    local major_minor="$(echo ${tag_name} | cut -d. -f1-2)"
+    local yaml_source_file="$(gsutil ls gs://knative-releases/${repo_name}/previous/${major_minor}.*/${yaml_name}.yaml \
+      | sort \
+      | tail -n 1 \
+      | sed 's/gs:\/\//https:\/\/storage.googleapis.com\//')"
```
Comment (adrcunha) [inline scripts/library.sh]: Use `cut -b6-` to remove the `gs://` prefix, then add the https and domain; this will be more readable than the see command.

Comment (Fredy-Z) [reply scripts/library.sh]: Done.
